export const CATEGORY_IMAGE_MAX_SIZE_BYTES = 10 * 1024 * 1024;
export const CATEGORY_IMAGE_MAX_SIZE_LABEL = "10 МБ";

export const PUBLIC_IMAGE_MAX_SIZE_BYTES = CATEGORY_IMAGE_MAX_SIZE_BYTES;
export const PUBLIC_IMAGE_MAX_SIZE_LABEL = CATEGORY_IMAGE_MAX_SIZE_LABEL;
